name: stallworks-system

services:
  # ---------- databases ----------
  auth-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${AUTH_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CORE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${CORE_DB_PORT}:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${CORE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- db admin UI ----------
  pgadmin:
    image: dpage/pgadmin4:9.4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      auth-db:
        condition: service_healthy
      core-db:
        condition: service_healthy

  # ---------- application services ----------
  auth-service:
    build:
      context: ./services/auth-service
    profiles: ["apps"]
    restart: unless-stopped
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${AUTH_SERVICE_PORT}:8080"

  core-service:
    build:
      context: ./services/core-service
    profiles: ["apps"]
    restart: unless-stopped
    depends_on:
      core-db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://core-db:5432/${CORE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${CORE_SERVICE_PORT}:8080"

  # ---------- gateway ----------
  # api-gateway:
  #   build:
  #     context: ./gateway/api-gateway
  #   profiles: ["apps"]
  #   restart: unless-stopped
  #   depends_on:
  #     - auth-service
  #     - core-service
  #   environment:
  #     SERVER_PORT: 8080
  #     AUTH_URI: http://auth-service:8080
  #     CORE_URI: http://core-service:8080
  #   ports:
  #     - "8090:8080"

volumes:
  auth_db_data:
  core_db_data:
  pgadmin_data: