spring.application.name=auth-service

server.port=${SERVER_PORT:8081}

#============== Database Configuration ===============#
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stallworks}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stallworks}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.sql.init.mode=always


spring.web.error.include-message=always


jwt.secret=${JWT_SECRET:Nb1Yu58c639tX1YM4Oo+M17TLw/MAPO836pEZ5eDV3+a2uThYOwJ3QE0yeguhIQDjP69t2Exe3sdd9+F4/Fi3Q==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}


core-service.base-url=${CORE_SERVICE_URL:http://localhost:8082}