spring.application.name=auth-service

server.port=${SERVER_PORT:8081}

#============== Database Configuration ===============#
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stallworks}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stallworks}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.sql.init.mode=always