-- Dev-only seed account, mirrors core-service's seeded employee "Mhay"
-- (employeeId 2) — see R__seed_initial_data.sql in core-service.
--
-- Auth-service has no Flyway here (schema comes from
-- spring.jpa.hibernate.ddl-auto=update instead), so this runs as plain
-- Spring SQL init. spring.jpa.defer-datasource-initialization=true
-- (already set in application.properties) is what makes this safe —
-- it makes Spring wait until Hibernate has created/updated the schema
-- before running this file, avoiding the same "relation does not exist"
-- race that hit core-service's data.sql.
--
-- The password can't be generated by plain SQL — bcrypt hashing has to
-- happen through the app's PasswordEncoder — so this is a pre-computed
-- bcrypt hash of "mhay1234" (10 rounds), not the plaintext. Regenerate it
-- if the password below ever needs to change.
--
-- ON CONFLICT (user_name) DO NOTHING keeps this idempotent — safe to
-- leave running on every startup.

INSERT INTO accounts (user_name, password, employee_id, role, enabled, created_at, updated_at)
VALUES (
    'mhay',
    '$2b$10$1T0bcnLdyUCcc8aTDj63vOY52v7lWTgfcw0CZsv4RXEiqnx9E9GjK',
    2,
    'ADMIN',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (user_name) DO NOTHING;
