spring.application.name=core-services

server.port=${SERVER_PORT:8082}

#============== Database Configuration ===============#
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/core_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stallworks}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stallworks}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.sql.init.mode=always


