spring.application.name=core-services

server.port=8082


#==============DB Password=======================#
spring.datasource.url=jdbc:postgresql://localhost:5434/core_db
spring.datasource.username=stallworks
spring.datasource.password=stallworks

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.sql.init.mode=always